import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Navbar from "../component/navbar";

export default function Home() {
  const [displayProfil, setDisplayProfil] = useState(false);
  const [displayExperiences, setDisplayExperiences] = useState(false);
  const [displayFormation, setDisplayFormation] = useState(false);
  const [displayInterest, setDisplayInterest] = useState(false);
  const [displayInfoMe, setDisplayInfoMe] = useState(false);

  const profil = () => {
    setDisplayInterest(false);
    setDisplayFormation(false);
    setDisplayExperiences(false);
    setDisplayProfil(true);
    setDisplayInfoMe(false);
  };
  const experiences = () => {
    setDisplayInterest(false);
    setDisplayFormation(false);
    setDisplayExperiences(true);
    setDisplayProfil(false);
    setDisplayInfoMe(false);
  };
  const formation = () => {
    setDisplayInterest(false);
    setDisplayFormation(true);
    setDisplayExperiences(false);
    setDisplayProfil(false);
    setDisplayInfoMe(false);
  };
  const interets = () => {
    setDisplayInterest(true);
    setDisplayFormation(false);
    setDisplayExperiences(false);
    setDisplayProfil(false);
    setDisplayInfoMe(false);
  };
  const infoMe = () => {
    setDisplayInterest(false);
    setDisplayFormation(false);
    setDisplayExperiences(false);
    setDisplayProfil(false);
    setDisplayInfoMe(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CV Romuald LE CORROLLER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
          integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
          integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
          crossorigin="anonymous"
        ></script>
      </Head>
      <Navbar />

      <main className={styles.main}>
        <p className={styles.description}>
          <code className={styles.code}>
            Mon lien{" "}
            <a href="https://github.com/romualdrlc?tab=repositories">Github</a>
          </code>
        </p>

        <div className={styles.grid}>
          <h2
            className={styles.card}
            onClick={() => infoMe()}
            style={{ cursor: "pointer" }}
          >
            Informations personelles &rarr;
          </h2>
          <h2
            className={styles.card}
            onClick={() => profil()}
            style={{ cursor: "pointer" }}
          >
            Profil &rarr;
          </h2>

          <h2
            className={styles.card}
            onClick={() => experiences()}
            style={{ cursor: "pointer" }}
          >
            Experiences &rarr;
          </h2>

          <h2
            className={styles.card}
            onClick={() => formation()}
            style={{ cursor: "pointer" }}
          >
            Formation &rarr;
          </h2>

          <h2
            className={styles.card}
            onClick={() => interets()}
            style={{ cursor: "pointer" }}
          >
            Centre d'interêts &rarr;
          </h2>
        </div>
        {displayInfoMe ? (
          <div id="profil" className={styles.card}>
            <p>Je suis romuald, marié deux enfants, j'ai 43 ans</p>
            <p>Mon adresse : 2 franchaud 44440 a Joué sur Erdre.</p>
            <p>Mon mail: romuald.lecorroller@gmail.com</p>
            <p>Mon tel: 06 24 56 53 27</p>
          </div>
        ) : null}
        {displayProfil ? (
          <div id="profil" className={styles.card}>
            <p>
              Bonjour,
              <br /> je suis technicien dépanneur en micro-informatique depuis
              20 ans et j'ai décidé de changer de métiers. Je viens de faire une
              formation chez Fewlines pour devenir développeur web react et next
              js. Elle s'est déroulé durant 3 mois. Vous pourrez voir dans la
              partie experiences toutes les technos que j'ai pu utilisé.
            </p>
          </div>
        ) : null}
        {displayExperiences ? (
          <div id="experiences" className={styles.card}>
            <ul>
              <p>Formation développeur chez Fewlines a Lilles - 2021</p>
              <br />
              <li>Apprentissage React - Next js - Node- Express - Github</li>
              <br />
              <li>Apprentissage MongoDb - Heroku</li>
              <br />
              <li>Apprentissage Bootstrap - Nunjucks</li>
              <br />
              <li>
                Apprentissage Javascript - Typescript Apprentissage Html5 - CSS3
              </li>
              <br />
              <li> Apprentissage Jest et Taiko</li>
              <br />
            </ul>
            <ul>
              <p>
                Technicien dépanneur en informatique – Solvarea à Saint-Herblain
                (44)- 1999-2021
              </p>
              <li>
                Maintenance micro-informatique (desktop, notebook et tablette) ;
              </li>
              <br />
              <li>Réparation smartphone ; </li>
              <br />
              <li>
                Installation de systèmes informatique (remasterisation ou
                recovery) et matériels informatique
              </li>
              <br />
            </ul>
          </div>
        ) : null}
        {displayFormation ? (
          <div id="formation" className={styles.card}>
            <ul>
              <p>Parcours scolaire</p>
              <br />
              <li>
                2000 : Formation LEGRI (Responsable logiciel et gestion réseau)
                ecole polytechnique – Nantes (44)
              </li>
              <br />
              <li>
                1998 : BTS informatique industrielle mention économie lycée
                Nicolas Appert – Orvault (44){" "}
              </li>
              <br />
              <li>1996 : Baccalauréat sti - Nantes (44)</li>
              <br />
            </ul>
          </div>
        ) : null}
        {displayInterest ? (
          <div id="centre-interets" className={styles.card}>
            <ul>
              <p>Centre d'intérêts</p>
              <br />
              <li>Anglais informatique lu</li>
              <br />
              <li>
                Pratique du football et dirigeant, entraineur des u12-u13.
              </li>
              <br />
              <li>L’univers des nouvelles technologies.</li>
              <br />
            </ul>
          </div>
        ) : null}
      </main>

      <footer class="row">
        <div class="sozial col-12">
          <ul class="row">
            <li class="col-xs-6 col-sm-2">
              <a href="#">
                <img
                  class="logo"
                  src="https://cdn2.iconfinder.com/data/icons/black-white-social-media/32/online_social_media_google_plus-128.png"
                />
              </a>
            </li>
          </ul>
        </div>
      </footer>
    </div>
  );
}
